parameters:
    curlHelper.class:    Renaissance\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   IULKhnRJ2lVB5bza9NC70AUGnT9VtVaRgdt5737tlPhAGSMDVYcd7VBw9pfVR2GV
    curlHelper.class.base_url:   "https://canvas.example.com/api/v1/"
    curlHelper.class.authed:   FALSE
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]
    renaissance.twig.renaissance_extension:
        class: Renaissance\CommonBundle\Twig\RenaissanceExtension
        arguments:    [@service_container]
        tags:
            - { name: twig.extension }
    baseREST:
        class: Renaissance\CommonBundle\REST\BaseREST
        arguments: [@curlHelper,@service_container]
    courseREST:
        class: Renaissance\CommonBundle\REST\CourseREST
        parent: baseREST
    enrollmentREST:
        class: Renaissance\CommonBundle\REST\EnrollmentREST
        parent: baseREST
    userREST:
        class: Renaissance\CommonBundle\REST\UserREST
        parent: baseREST
    fileREST:
        class: Renaissance\CommonBundle\REST\FileREST
        parent: baseREST
    modulesREST:
        class: Renaissance\CommonBundle\REST\ModulesREST
        parent: baseREST
    pageREST:
        class: Renaissance\CommonBundle\REST\PageREST
        parent: baseREST

